# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9508a1e255eb1ec83f9caabdccbaf17d7515eff331ec21cd782ba74696321b821df6bd566ebbc9da0191d54e21ac722ad8310991cdd7d884a45ba85709bd78e6

test:
  secret_key_base: eedb2f4bbdf8b0e179be9471a69fe4634a11e435762d3abafa7fc9ec51329b6021501969c19577af351eb6fbbb63088ba1b194fd2e8efa92c0c0b29d62ff0f60

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
